include: package:lints/recommended.yaml

linter:
  rules:
    - avoid_futureor_void
    - await_only_futures
    - avoid_void_async
    - async_return_with_no_await
    - empty_container_bodies
    - initialize_in_field_declaration
    - parameter_assignments
    - prefer_relative_imports
    - unawaited_futures
    - unnecessary_async
    - unnecessary_const_in_enum_constructor
    - unnecessary_primary_constructor_body
    - unnecessary_type_name_in_constructor
    - use_declaring_parameters