name: benchmark_runner

description: A library for writing inline micro-benchmarks, running sync/async
  benchmarks, reporting and exporting score statistics.

version: 0.2.0

homepage: https://github.com/simphotonics/benchmark_runner

executables:
  # <command-name>:<script-name>
  benchmark_runner: benchmark_runner

topics:
  - benchmark
  - async
  - inline
  - histogram
  - statistics

environment:
  sdk: '^3.0.0'

dependencies:
  ansi_modifier: ^0.1.4
  args: ^2.5.0
  benchmark_harness: ^2.2.2
  exception_templates: ^0.3.1
  lazy_memo: ^0.2.3
  path: ^1.9.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.8
  test_process: ^2.1.0
