name: benchmark_runner

description: A library for writing inline
   micro-benchmarks, reporting score statistics, and running
   sync/async benchmarks.

version: 0.0.2

homepage: https://github.com/simphotonics/benchmark_runner

executables:
  benchmark_runner: benchmark_runner

topics:
  - benchmark
  - async
  - inline
  - histogram
  - statistics

environment:
  sdk: '^3.0.0'

dependencies:
  ansi_modifier: ^0.1.1
  benchmark_harness: ^2.2.2
  exception_templates: ^0.3.0
  lazy_memo: ^0.2.2

dev_dependencies:
  lints: ^2.1.1
  test: ^1.24.6
